### ISSUE TITLE
If you set custom padding, it will broke the button.

### ISSUE THREAD

**Issue by vladi160** [hakimel/Ladda#97]
You can check and in your examples. If you set for the example `padding: 14px 18px; ` to the `expand-right` it will be broken.

**Comment by stevebauman** [comment]
This isn't a bug - it's due to how CSS works. If you set padding on the element itself (for example, using the `style` attribute), then this has a higher precedence than the styles applied by the `data-loading` CSS selector from the `ladda.css` file, so it's padding stays static and is not being changed dynamically with Ladda.

Use utility classes instead of using the `style` attribute.
